import "./globals.css";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://bootswatch.com/5/litera/bootstrap.min.css"
        />
      </head>

      <body>
        <NavBar />
          <div className="container p-6">{children}</div>
        <Footer />
      </body>
      </html>
      </ClerkProvider>
  );
}
